---
- hosts: all
  become: yes
  tasks:

    - name: Copy a new sudoers file into place, after passing validation with visudo
      ansible.builtin.copy:
        src: sudo.conf
        dest: /etc/sudoers.d/passwordless_sudo
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -csf %s
