---
- hosts: all
  become: yes
  tasks:

    - name: Copy a new sudoers file into place, after passing validation with visudo
      ansible.builtin.copy:
        src: sudo.conf
        dest: /etc/sudoers.d/passwordless_sudo
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -csf %s

    - name: Erzwinge Passwortlänge auf 14 Zeichen
      ansible.builtin.blockinfile:
        path: /etc/security/pwquality.conf.d/pwsettings.conf
        block: |
          minlen = 14
        create: true
        owner: root
        group: root
        mode: '0644'
