---
- hosts: all
  become: yes
  tasks:
    - name: Creating passwordless sudo permissions for wheel group
      copy:
        dest: "/etc/sudoers.d/passwordless_sudo_for_wheel_group"
        content: |
          %wheel	ALL=(ALL)	NOPASSWD: ALL

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/sudoers.d/passwordless_sudo_for_wheel_group
        owner: root
        group: root
        mode: "0440"
