---
- hosts: all
  become: yes
  environment:

  tasks:
    # rpm_key funktioniert nicht mit Proxy!
    # - name: Add nagios gpg key V2
    #   rpm_key:
    #     key: https://repo.nagios.com/GPG-KEY-NAGIOS-V2
    #     state: present

    - name: Add nagios gpg key V2
      ansible.builtin.command: rpm --import https://repo.nagios.com/GPG-KEY-NAGIOS-V2 --httpproxy {{ proxy_hostname }} --httpport {{ proxy_port }}

    # rpm_key funktioniert nicht mit Proxy!
    # - name: Add nagios gpg key V3
    #   rpm_key:
    #     key: https://repo.nagios.com/GPG-KEY-NAGIOS-V3
    #     state: present

    - name: Add nagios gpg key V3
      ansible.builtin.command: rpm --import https://repo.nagios.com/GPG-KEY-NAGIOS-V3 --httpproxy {{ proxy_hostname }} --httpport {{ proxy_port }}

    - name: Add nagios repository
      ansible.builtin.dnf:
        name: "https://repo.nagios.com/nagios/9/nagios-repo-9-2.el9.noarch.rpm"
        state: present

    - name: Install nagios package
      ansible.builtin.dnf:
        name:
          - ncpa
        state: present
        update_cache: true

    - name: nagios Konfiguration bearbeiten
      ansible.builtin.template:
        src: ncpa.j2
        dest: /usr/local/ncpa/etc/ncpa.cfg
        owner: root
        group: nagios
        mode: "0640"

    - name: Port 5693 in der Firewall öffnen
      ansible.posix.firewalld:
        rich_rule: rule family=ipv4 source address={{ nagios_source }} port port="5693" protocol=tcp accept
        permanent: true
        immediate: true
        state: enabled

    - name: Restart nagios Service
      service:
        name: ncpa
        state: restarted
