---
- hosts: all
  become: yes
  tasks:
    - name: Erstelle Benutzer {{ create_user }}
      ansible.builtin.user:
        name: "{{ create_user }}"
        create_home: yes
        groups: wheel
        shell: /bin/bash
        append: yes
#        password_expire_min: 0
#        password_expire_max: 90
#        password_expire_warn: 14
      notify:
        - Initialpasswort erstellen
        - Passwortneuvergabe erzwingen

    - name: Proxy in .bashrc eintragen
      ansible.builtin.blockinfile:
        path: /home/{{ create_user}}/.bashrc
        block: |
          export http_proxy={{ proxy_url }}
          export https_proxy=$http_proxy
          export ftp_proxy=$http_proxy

  handlers:
    - name: Initialpasswort erstellen
      ansible.builtin.user:
        name: "{{ create_user }}"
        password: "{{ 'changeme' | password_hash('sha512') }}"

    - name: Passwortneuvergabe erzwingen
      ansible.builtin.command: passwd -e {{ create_user }}
