---
- hosts: all
  become: yes
  vars:
    createpassword: 'changeme'

  tasks:
    - name: Erstelle Benutzer '{{ create_user }}'
      ansible.builtin.user:
        name: "{{ create_user }}"
        create_home: yes
        groups: wheel
        shell: /bin/bash
        append: yes
        password_expire_min: 0
        password_expire_max: 365
        password_expire_warn: 14 # benötigt ansible-core >=2.16
      notify:
        - Initialpasswort erstellen
        - Passwortneuvergabe erzwingen

  handlers:
    - name: Initialpasswort erstellen
      shell: usermod -p $(echo '{{ createpassword }}' | openssl passwd -1 -stdin) {{ create_user }}

    - name: Passwortneuvergabe erzwingen
      ansible.builtin.command: passwd -e {{ create_user }}
