---
- hosts: all
  become: yes
  tasks:
    - name: Erstelle Benutzer {{ create_user }}
      ansible.builtin.user:
        name: "{{ create_user }}"
        create_home: yes
        password: "{{ 'changeme' | password_hash('sha512') }}"
        groups: wheel
        shell: /bin/bash
        append: yes

    - name: Proxy in .bashrc eintragen
      ansible.builtin.blockinfile:
        path: /home/{{ create_user}}/.bashrc
        block: |
           export http_proxy={{ dnf_proxy }}
           export https_proxy=$http_proxy
           export ftp_proxy=$http_proxy

# Passwortablauf
