---
- hosts: dmz
  become: yes
  tasks:
    # https://docs.fedoraproject.org/en-US/epel/getting-started/
    - name: Enable a RHSM repository (redhat)
      community.general.rhsm_repository:
        name: codeready-builder-for-rhel-9-x86_64-rpms
      when: ansible_distribution == "RedHat"

    - name: Import the epel repo key from a url (redhat)
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
      when: ansible_distribution == "RedHat"

    - name: Install the epel repo (redhat)
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: latest
      when: ansible_distribution == "RedHat"

# rocky epel.repo anpassen (baseurl statt mirrorlist)

    - name: Install syslog-ng
      ansible.builtin.dnf:
        name:
          - syslog-ng
        state: present
        update_cache: true

    - name: syslog-ng starten
      service:
        name: syslog-ng
        state: started
        enabled: true

    - name: rsyslog deaktivieren
      service:
        name: rsyslog
        state: stopped
        enabled: false

# firewall-cmd --info-service=syslog-tls
    - name: syslog-tls Ports in der Firewall öffnen
      ansible.posix.firewalld:
        service: syslog-tls
        permanent: true
        immediate: true
        state: enabled
