---
- hosts: all
  become: yes
  tasks:
    - name: Update only security related packages to their latest version
      ansible.builtin.dnf:
        name: "*"
        security: true
        update_cache: true
        state: latest
