---
- hosts: all
  become: yes
  tasks:
    - name: Remove podman and runc (redhat)
      ansible.builtin.dnf:
        name:
          - podman
          - runc
        state: absent
      when: ansible_distribution == "RedHat"

    - name: Add docker gpg key (rocky)
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
      when: ansible_distribution == "Rocky"

    - name: Add docker gpg key (redhat)
      rpm_key:
        key: https://download.docker.com/linux/rhel/gpg
        state: present
      when: ansible_distribution == "RedHat"

    - name: Add docker repository (rocky)
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution == "Rocky"

    - name: Add docker repository (redhat)
      get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution == "RedHat"

    - name: Install docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Add a user to the docker group
      ansible.builtin.user:
        name: joe
        groups: docker
        append: yes

    - name: docker Service starten
      service:
        name: docker
        state: started
        enabled: true

    - name: Erstelle Verzeichis für Docker Grundgerüst
      ansible.builtin.file:
        path: /home/joe/docker/base
        state: directory
      become: yes 
      become_user: joe

    - name: Kopiere Compose Datei
      ansible.builtin.copy:
        src: compose-base.yml
        dest: /home/joe/docker/base/docker-compose.yml
        owner: joe
        group: joe
        mode: '0644'
      become: yes 
      become_user: joe 

    - name: Erstelle Basiscontainer
      ansible.builtin.shell: cd /home/joe/docker/base && docker compose up -d
      become: yes 
      become_user: joe 
