---
- hosts: all
  become: yes
  tasks:
    - name: Remove podman and runc (redhat)
      ansible.builtin.dnf:
        name:
          - podman
          - runc
        state: absent
      when: ansible_distribution == "RedHat"

    - name: Add docker gpg key (rocky)
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
      when: ansible_distribution == "Rocky"

    - name: Add docker gpg key (redhat)
      rpm_key:
        key: https://download.docker.com/linux/rhel/gpg
        state: present
      when: ansible_distribution == "RedHat"

    - name: Add docker repository (rocky)
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution == "Rocky"

    - name: Add docker repository (redhat)
      get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution == "RedHat"

    - name: Install docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Benutzer der Docker Gruppe hinzuf端gen
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    - name: Erstelle Verzeichis f端r Docker Proxykonfiguration
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory 

    - name: Docker Proxykonfiguration erstellen
      ansible.builtin.template:
        src: docker-proxy.j2
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf

    - name: docker Service starten
      service:
        name: docker
        state: started
        enabled: true

    - name: Erstelle Verzeichis f端r Docker Grundger端st
      ansible.builtin.file:
        path: /home/{{ docker_user }}/docker/base
        state: directory
      become: yes
      become_user: "{{ docker_user }}"

    - name: Kopiere Compose Datei
      ansible.builtin.copy:
        src: compose-base.yml
        dest: /home/{{ docker_user }}/docker/base/docker-compose.yml
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: "0644"
      become: yes
      become_user: "{{ docker_user }}"

    # reset_connection doesn't support conditionals.
    - name: Reset connection so docker group is picked up
      meta: reset_connection

    - name: Erstelle die Basiscontainer
      ansible.builtin.shell: 
        cmd: docker compose up -d
        chdir: /home/{{ docker_user }}/docker/base 
      become: yes
      become_user: "{{ docker_user }}"
