---
- hosts: all
  become: yes
  tasks:
    - name: Ports in der Firewall schliessen
      ansible.posix.firewalld:
        port: "{{ item }}"
#        rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
        permanent: true
        immediate: true
        state: disabled
      loop:
        - 80/tcp
        - 81/tcp
