---
- hosts: all
  become: yes
  tasks:
    - name: Ports in der Firewall öffnen
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - 8000/tcp
        - 9997/tcp
        - 8089/tcp
