---
- hosts: dmz
  become: yes
  tasks:
    - name: UF rpm auf Server kopieren
      ansible.builtin.copy:
        src: uf-9.4.1.rpm
        dest: /tmp/uf-9.4.1.rpm

    - name: Splunk pgp Key auf Server kopieren
      ansible.builtin.copy:
        src: SplunkPGPKey.pub
        dest: /tmp/SplunkPGPKey.pub

    - name: Add splunk pgp key
      ansible.builtin.command: rpm --import /tmp/SplunkPGPKey.pub

    - name: Installation von Splunk Forwarder
      ansible.builtin.dnf:
        name: /tmp/uf-9.4.1.rpm
        state: present
      notify:
        - Erstelle Credentials
        - Initialer Start von SplunkForwarder
        - Ports in der Firewall öffnen
        - SplunkForwarder starten

  handlers:
    - name: Erstelle Credentials
      ansible.builtin.blockinfile:
        path: /opt/splunkforwarder/etc/system/local/user-seed.conf
        block: |
          [user_info]
          USERNAME = {{ splunk_user }}
          PASSWORD = {{ splunk_password }}
        create: true
        owner: splunkfwd
        group: splunkfwd
        mode: "0400"

    - name: Initialer Start von SplunkForwarder
      ansible.builtin.command: /opt/splunkforwarder/bin/splunk start --accept-license --no-prompt

    - name: SplunkForwarder starten
      service:
        name: SplunkForwarder
        state: started
        enabled: true
