---
- hosts: dmz
  become: yes
  tasks:
    - name: UF rpm auf Server kopieren
      ansible.builtin.copy:
        src: uf-9.4.0.rpm
        dest: /tmp/uf-9.4.0.rpm

#     rpm_key funktioniert nicht mit Proxy!
    - name: Add splunk pgp key
      rpm_key:
        key: https://docs.splunk.com/images/6/6b/SplunkPGPKey.pub
        state: present

#    - name: Add splunk pgp key
#      ansible.builtin.command: rpm --import https://docs.splunk.com/images/6/6b/SplunkPGPKey.pub --httpproxy {{ proxy_hostname }} --httpport {{ proxy_port }}

    - name: Installation von Splunk Forwarder
      ansible.builtin.dnf:
        name: /tmp/uf-9.4.0.rpm
        state: present
      notify:
        - Erstelle Credentials
        - Initialer Start von SplunkForwarder
        - Ports in der Firewall öffnen
        - SplunkForwarder starten

  handlers:
    - name: Erstelle Credentials
      ansible.builtin.blockinfile:
        path: /opt/splunkforwarder/etc/system/local/user-seed.conf
        block: |
          [user_info]
          USERNAME = {{ splunk_user }}
          PASSWORD = {{ splunk_password }}
        create: true
        owner: splunkfwd
        group: splunkfwd
        mode: "0400"

    - name: Initialer Start von SplunkForwarder
      ansible.builtin.command: /opt/splunkforwarder/bin/splunk start --accept-license --no-prompt

    - name: Ports in der Firewall öffnen
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - 9997/tcp

    - name: SplunkForwarder starten
      service:
        name: SplunkForwarder
        state: started
        enabled: true
